googleAnalytics = "UA-167958784-1"

baseURL = "https://covid19.compute.dtu.dk"
languageCode = "en-us"
title = "COVID-19 mobility"

[params]
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = false

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'dtu.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle = '/menu'

    # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = false

  # Set page weight to re-arrange items in file-tree menu (if BookMenuBundle not set)
  weight = 10
  country = "Denmark"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
